import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { runInNewContext } from 'node:vm'
import ts from 'typescript'
import { defineRouting } from 'next-intl/routing'

function load(path, modules) {
  const exports = {}
  const source = ts.transpileModule(readFileSync(new URL(path, import.meta.url), 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS },
  }).outputText
  runInNewContext(source, { exports, URL, require: (name) => modules[name] })
  return exports
}

const constants = { SITE_URL: 'https://anassalem.com' }
const { routing } = load('../i18n/routing.ts', { 'next-intl/routing': { defineRouting } })
const pathRequests = []
// Navigation is supplied at this boundary; production HTTP checks cover next-intl itself.
const getPathname = ({ locale, href }) => {
  pathRequests.push({ locale, href })
  return `/${locale}${href === '/' ? '' : href}`
}
const seo = load('../lib/seo.ts', {
  '@/lib/constants': constants,
  '@/i18n/navigation': { getPathname },
})
const { DATA } = load('../data/resume.ts', { '@/components/icons': { Icons: {} } })

test('localized SEO URLs delegate their paths to the navigation API', () => {
  assert.equal(seo.localizedUrl('/', 'en'), 'https://anassalem.com/en')
  assert.equal(seo.localizedUrl('/', 'ar'), 'https://anassalem.com/ar')
  assert.equal(seo.localizedUrl('/projects/vital', 'en'), 'https://anassalem.com/en/projects/vital')
  assert.deepEqual(pathRequests.at(-1), { locale: 'en', href: '/projects/vital' })
  assert.notEqual(routing.alternateLinks, false, 'Native next-intl alternate links remain enabled')
})

test('every localized page uses a self-canonical URL generated by next-intl', () => {
  const paths = [
    '/',
    '/projects',
    '/privacy',
    ...DATA.projects.cards.map((p) => `/projects/${p.id}`),
  ]
  for (const path of paths) {
    for (const locale of ['en', 'ar']) {
      const metadata = seo.pageMetadata({
        locale,
        path,
        title: 'Title',
        description: 'Description',
      })
      assert.equal(
        metadata.alternates.canonical,
        new URL(getPathname({ locale, href: path }), constants.SITE_URL).href,
      )
      assert.equal(metadata.alternates.languages, undefined)
      assert.equal(metadata.openGraph.url, metadata.alternates.canonical)
      assert.equal(metadata.twitter.title, metadata.openGraph.title)
      assert.equal(metadata.twitter.description, metadata.description)
      assert.deepEqual(metadata.twitter.images, metadata.openGraph.images)
      assert.equal(
        metadata.openGraph.images[0].url,
        `https://anassalem.com/images/og/${locale}.jpg`,
      )
    }
  }
})

test('project social previews and breadcrumb destinations match the localized detail page', () => {
  const metadata = seo.pageMetadata({
    locale: 'ar',
    path: '/projects/vital',
    title: 'Vital',
    description: 'Case study',
    image: { url: '/images/projects/vital/hero.jpg', alt: 'Vital website' },
  })
  assert.equal(
    metadata.openGraph.images[0].url,
    'https://anassalem.com/images/projects/vital/hero.jpg',
  )
  assert.equal(metadata.twitter.images[0].alt, 'Vital website')
  assert.equal(metadata.openGraph.locale, 'ar_AE')
  const crumbs = seo.projectBreadcrumbs('ar', 'Vital', 'vital').itemListElement
  assert.equal(crumbs[0].item, 'https://anassalem.com/ar')
  assert.equal(crumbs[1].item, 'https://anassalem.com/ar/projects')
  assert.equal(crumbs[2].item, metadata.alternates.canonical)
})

test('sitemap lists each page in both languages using native next-intl paths', () => {
  const sitemap = load('../app/sitemap.ts', {
    '@/data/resume': { DATA },
    '@/i18n/routing': { routing },
    '@/lib/seo': seo,
  }).default()
  assert.equal(sitemap.length, (DATA.projects.cards.length + 3) * 2)
  assert.equal(new Set(sitemap.map((entry) => entry.url)).size, sitemap.length)
  for (const entry of sitemap) {
    assert.ok(
      entry.url.startsWith('https://anassalem.com/en') ||
        entry.url.startsWith('https://anassalem.com/ar'),
    )
  }
  for (const locale of ['en', 'ar']) {
    const messages = JSON.parse(
      readFileSync(new URL(`../messages/${locale}.json`, import.meta.url)),
    )
    for (const project of DATA.projects.cards) {
      assert.ok(
        messages.seo.projectDescriptions[project.id],
        `${locale}: ${project.id} needs a description`,
      )
    }
  }
})

test('structured data cannot terminate its script tag and still round-trips correctly', () => {
  const payload = { name: '</script><script>alert(1)</script>' }
  const serialized = seo.serializeJsonLd(payload)
  assert.ok(!serialized.includes('<'))
  assert.deepEqual(JSON.parse(serialized), payload)
})
